### ISSUE TITLE
Results page breaks under certain conditions.

### ISSUE THREAD

**Issue by mayankchetan** [deslaughter/acdc-app#2]
Results tab has been breaking under certain conditions, need to restart app after that point. Listing them as I find them below:

### 1. When using the Swap function.
- Click on a OP on the Campbell Diagram. Swap with another line. Results page may break.

### 2. When visualizing one of the last OPs for a line.
- Generate viz for any OP, then select last OP on a different line and generate viz

**Comment by deslaughter** [comment]
Thanks for tracking these down and providing clear steps to reproduce. Please try the latest version built with Github actions and see if the issues are resolved.

**Comment by deslaughter** [comment]
I've created a v0.3.0-alpha release which resolves this issue.
