### ISSUE TITLE
Add Copy feature for Analysis cases

### ISSUE THREAD

**Issue by mayankchetan** [deslaughter/acdc-app#3]
Feature requests based on using the tool, will update over time:

- [ ] A "Copy" feature in analysis to make a copy of a previously defined case.
       - Use case: Incase the user makes edits to the model, eg: switching from ElastoDyn --> BeamDyn. Would be nice to make a new case, copying over the OP's from the previous one.

**Comment by deslaughter** [comment]
I took a quick stab at implementing the duplicate feature. Please try it out in the latest version built on Github Actions.

**Comment by deslaughter** [comment]
This feature has been included in thev0.3.0-alpha release.
