### ISSUE TITLE
SttsTime sets itself to 6, ignoring user input

### ISSUE THREAD

**Issue by mayankchetan** [deslaughter/acdc-app#4]
SttsTime is set a 6-seconds and does not change based on user input on 'Model' tab. Will be useful to be lower when using BeamDyn.

Input in ACDC
![image](https://github.com/deslaughter/acdc-app/assets/4620557/618b6790-ea36-4d77-a102-d37e148639e7)

OpenFAST file generated:
![image](https://github.com/deslaughter/acdc-app/assets/4620557/af5c4502-7e06-42b4-a4fc-bddee1b40c96)

**Comment by deslaughter** [comment]
This is being automatically set to give 50 increments on the progress bars. I hadn't really considered having it set lower than that, but it may make sense on really slow simulations where the user needs more feedback. I'll change this to be the minimum of the user input and the value calculated to give approximately 100 status messages over the full simulation time.

**Comment by deslaughter** [comment]
I looked into this a little further, and while the SttsTime can be set to a value less than 1 second, the output message only has a one second resolution but it will repeat the same message multiple times. I have changed the status time calculation to pick the minimum of what the user sets or ceil(TMax/100). This has been implemented in the v0.3.0-alpha release.
