### ISSUE TITLE
"Model" tab doesn't work

### ISSUE THREAD

**Issue by verlivkra** [deslaughter/acdc-app#6]
First of all: Thanks a lot for this very useful tool!

On my Windows computer, when hitting the "Model" tab after creating a new project, the Model page is completely blank, with no option to import an OpenFAST model. 
In a previous version, where the tab was named "Turbine", everything worked well (I could import an OpenFAST Turbine).

**Comment by deslaughter** [comment]
@verlivkra I was able to reproduce the issue and fix it in the v0.3.0-alpha release. Please give it a try.

**Comment by verlivkra** [comment]
@deslaughter The Model tab now lets me choose an OpenFAST file. However, after choosing the file, in a previous version of acdc, there would be a list of imported files. This doesn't show up now. 
Moreover, when trying to run an analysis, the app crashes (probably not related, so let me know if I should open a separate issue on this).

**Comment by deslaughter** [comment]
I was able to reproduce the issue when importing a model that doesn't use SubDyn. The array of SubDyn files wasn't being initialized properly if none were imported. As in the previous versions, after the OpenFAST model is imported, you should see a list of the files that it read. Please try an updated executable from the bottom of https://github.com/deslaughter/acdc-app/actions/runs/9082652159. ACDC is built on every push by Github Actions, so you can look at https://github.com/deslaughter/acdc-app/actions to get the latest version. Once v1.0 is stable and released, we'll have a more consistent development process.

**Comment by deslaughter** [comment]
Moving ACDC to it's new home under the OpenFAST organization at https://github.com/OpenFAST/acdc. Please open a new issue there if this hasn't been resolved by the v0.4.0 release in the new repo
