### ISSUE TITLE
SubDyn filename in generated .fst-file and name of SubDyn-file in folder not compatible

### ISSUE THREAD

**Issue by verlivkra** [deslaughter/acdc-app#7]
I have the following input files listed in my **base** (imported) .fst-file:

---------------------- INPUT FILES ---------------------------------------------
"RWT_ElastoDyn.dat" EDFile        - Name of file containing ElastoDyn input parameters (quoted string)
"unused"          BDBldFile(1)  - Name of file containing BeamDyn input parameters for blade 1 (quoted string)
"unused"          BDBldFile(2)  - Name of file containing BeamDyn input parameters for blade 2 (quoted string)
"unused"          BDBldFile(3)  - Name of file containing BeamDyn input parameters for blade 3 (quoted string)
"RWT_InflowFile.dat" InflowFile    - Name of file containing inflow wind input parameters (quoted string)
"unused" 		  AeroFile      - Name of file containing aerodynamic input parameters (quoted string)
"Control\RWT_ServoDyn.dat" ServoFile     - Name of file containing control and electrical-drive input parameters (quoted string)
"Substructure\RWT_ElastoDyn_tower_HydroDyn_StillWater.dat"         HydroFile     - Name of file containing hydrodynamic input parameters (quoted string)
"Substructure\RWT_ElastoDyn_tower_SubDyn.dat"     SubFile       - Name of file containing sub-structural input parameters (quoted string)
"unused"          MooringFile   - Name of file containing mooring system input parameters (quoted string)
"unused"          IceFile       - Name of file containing ice input parameters (quoted string)

In the new **case** .fst-file, the SubDyn file is named as following (for case01):

---------------------- INPUT FILES ---------------------------------------------
"01_RWT_ElastoDyn.dat"   EDFile          - Name of file containing ElastoDyn input parameters (quoted string)
"01_FileNotFound"   BDBldFile(1)    - Name of file containing BeamDyn input parameters for blade 1 (quoted string)
"01_FileNotFound"   BDBldFile(2)    - Name of file containing BeamDyn input parameters for blade 2 (quoted string)
"01_FileNotFound"   BDBldFile(3)    - Name of file containing BeamDyn input parameters for blade 3 (quoted string)
"01_FileNotFound"   InflowFile      - Name of file containing inflow wind input parameters (quoted string)
"01_FileNotFound"   AeroFile        - Name of file containing aerodynamic input parameters (quoted string)
"01_RWT_ServoDyn.dat"   ServoFile       - Name of file containing control and electrical-drive input parameters (quoted string)
"01_RWT_ElastoDyn_tower_HydroDyn_StillWater.dat"   HydroFile       - Name of file containing hydrodynamic input parameters (quoted string)
_"01_RWT_ElastoDyn_tower_SubDyn.dat"_   SubFile         - Name of file containing sub-structural input parameters (quoted string)
"FileNotFound"   MooringFile     - Name of file containing mooring system input parameters (quoted string)
"FileNotFound"   IceFile         - Name of file containing ice input parameters (quoted string)

However, in the case01 **folder**, there is no file named "01_RWT_ElastoDyn_tower_SubDyn.dat", but rather a file named "RWT_ElastoDyn_tower_SubDyn.dat". lt seems the SubDyn-file is copied as a file that is common between the cases, but then the renaming in the reference to the SubDyn-file in the .fst-file is wrong. 

Note that I am using an older version of acdc, as I was not able to make the v020_alpha version work (ref previous issue). 

Let me know if anything is unclear. And again, I really appreciate this tool.

**Comment by deslaughter** [comment]
@verlivkra The SubDyn files were being treated as miscellaneous files (like the airfoil info files), which are assumed not to change between cases. This was a result of having not tested with models which use SubDyn input files. A new example case has been added for a model which uses SubDyn and the issue you described has been corrected in v0.3.0-alpha. Please give it a try and let me know if this issue has been resolved.

**Comment by deslaughter** [comment]
Moving ACDC to it's new home under the OpenFAST organization at https://github.com/OpenFAST/acdc. Please open a new issue there if this hasn't been resolved by the v0.4.0 release in the new repo
